=== MarynaRomanets/WebServices/WebServices_JAXP_SAX/task1/src/cyberbionic/webservices/medicine.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="medicines" type="medicinesType"/>
  <xs:complexType name="analogsType">
    <xs:sequence>
      <xs:element name="analog" maxOccurs="unbounded" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="A"/>
            <xs:enumeration value="B"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="certificateType">
    <xs:sequence>
      <xs:element name="number">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="12345"/>
            <xs:enumeration value="123"/>
            <xs:enumeration value="980"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="date_start">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="2020-02-10"/>
            <xs:enumeration value="2020-10-02"/>
            <xs:enumeration value="2021-01-01"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="date_end">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="2021-02-10"/>
            <xs:enumeration value="2020-10-03"/>
            <xs:enumeration value="2025-01-01"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="registration">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="registrator1"/>
            <xs:enumeration value="registrator2"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="packageType">
    <xs:sequence>
      <xs:element name="type">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="box"/>
            <xs:enumeration value="tube"/>
            <xs:enumeration value="sticker"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="amount">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="13"/>
            <xs:enumeration value="123"/>
            <xs:enumeration value="4"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="price">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="6.5"/>
            <xs:enumeration value="34.9"/>
            <xs:enumeration value="56.0"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="dosageType">
    <xs:sequence>
      <xs:element name="dose">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="0.5"/>
            <xs:enumeration value="1.0"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="schedule">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="3"/>
            <xs:enumeration value="5"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="manufacturerType">
    <xs:sequence>
      <xs:element name="manufaturer_name">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="first"/>
            <xs:enumeration value="gghhh"/>
            <xs:enumeration value="sdfgh"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="certificateType" name="certificate"/>
      <xs:element type="packageType" name="package"/>
      <xs:element type="dosageType" name="dosage"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="versionType">
    <xs:sequence>
      <xs:element name="consistention">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="tablet"/>
            <xs:enumeration value="capsule"/>
            <xs:enumeration value="powder"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="manufacturerType" name="manufacturer"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="versionsType">
    <xs:sequence>
      <xs:element type="versionType" name="version" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="medicineType">
    <xs:sequence>
      <xs:element type="xs:string" name="name"/>
      <xs:element type="xs:string" name="pharm"/>
      <xs:element type="xs:string" name="group"/>
      <xs:element type="analogsType" name="analogs"/>
      <xs:element type="versionsType" name="versions"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="medicinesType">
    <xs:sequence>
      <xs:element type="medicineType" name="medicine"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== MarynaRomanets/WebServices/WebServices_JAXP_DOM/task1/src/cyberbionic/webservices/medicine.xml
<?xml version="1.0" encoding="UTF-8"?>

<medicines  xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
            xs:noNamespaceSchemaLocation="medicine.xsd">

    <medicine>
        <name>asd</name>
        <pharm>pharm1</pharm>
        <group>antibiotic</group>
        <analogs>
            <analog>A</analog>
            <analog>B</analog>
        </analogs>
        <versions>
            <version>
                <consistention>tablet</consistention>
                <manufacturer>
                    <manufaturer_name>first</manufaturer_name>
                    <certificate>
                        <number>12345</number>
                        <date_start>2020-02-10</date_start>
                        <date_end>2021-02-10</date_end>
                        <registration>registrator1</registration>
                    </certificate>
                    <package>
                        <type>box</type>
                        <amount>13</amount>
                        <price>6.5</price>
                    </package>
                    <dosage>
                        <dose>0.5</dose>
                        <schedule>3</schedule>
                    </dosage>
                </manufacturer>
            </version>
            <version>
                <consistention>capsule</consistention>
                <manufacturer>
                    <manufaturer_name>gghhh</manufaturer_name>
                    <certificate>
                        <number>123</number>
                        <date_start>2020-10-02</date_start>
                        <date_end>2020-10-03</date_end>
                        <registration>registrator2</registration>
                    </certificate>
                    <package>
                        <type>tube</type>
                        <amount>123</amount>
                        <price>34.9</price>
                    </package>
                    <dosage>
                        <dose>1.0</dose>
                        <schedule>5</schedule>
                    </dosage>
                </manufacturer>
            </version>
            <version>
                <consistention>powder</consistention>
                <manufacturer>
                    <manufaturer_name>sdfgh</manufaturer_name>
                    <certificate>
                        <number>980</number>
                        <date_start>2021-01-01</date_start>
                        <date_end>2025-01-01</date_end>
                        <registration>registrator2</registration>
                    </certificate>
                    <package>
                        <type>sticker</type>
                        <amount>4</amount>
                        <price>56.0</price>
                    </package>
                    <dosage>
                        <dose>0.5</dose>
                        <schedule>3</schedule>
                    </dosage>
                </manufacturer>
            </version>

        </versions>
    </medicine>

</medicines>
